### ISSUE TITLE
Importing alongside RcppArmadillo

### ISSUE THREAD

**Issue by mkln** [RInstitute/rcpparrayfire#17]
When building a package that is intended to use both RcppArmadillo and RcppArrayFire, this error appears:

```
In file included from RcppExports.cpp:5:0:
/home/mkln/R/x86_64-pc-linux-gnu-library/3.6/RcppArrayFire/include/RcppArrayFire.h:26:6: error: #error "The file 'Rcpp.h' should not be included. Please correct to include only 'RcppArrayFire.h'."
     #error "The file 'Rcpp.h' should not be included. Please correct to include only 'RcppArrayFire.h'."
```

I think it should be possible to use both in the same package (if not, why?)

**Comment by rstub** [comment]
Both RcppArmadillo and RcppArrayFire extend Rcpp's automatic type conversion system, allowing for the types from the respective libraries to be used in the function signatures of exported functions. This requires extension of `Rcpp::as` and `Rcpp::wrap`, which has to be done after including `RcppCommon.h` but before including `Rcpp.h`, c.f. the "Rcpp Extending" vignette.

`RcppArmadillo.h`  has a safe guard to disallow including it after `Rcpp.h` has been included, and `RcppArrayFire.h` has inherited that (interestingly `RcppEigen.h` dos not have that). This makes it impossible to use both headers at the same time. As alternative you could create a new header file in your package like

```cpp
#include <RcppArmadilloForward.h>
#include <RcppArrayFireForward.h>

#include <Rcpp.h>

#include <RcppArmadilloWrap.h>
#include <RcppArmadilloAs.h>
#include <RcppArmadilloSugar.h>

#include <RcppArrayFireWrap.h>
#include <RcppArrayFireAs.h>
```
Including this header *instead* of `RcppArmadillo.h` and `RcppArrayFire.h` should give you all the functionality from these two packages.

Can you tell me more about your use-case? Why do you want to use  both Armadillo and ArrayFire?

**Comment by mkln** [comment]
Thanks,  that worked. Instead of adding RcppArmadillo in LinkingTo I changed the Makevars.in to have 

`PKG_CPPFLAGS = $(AF_CXXFLAGS) -I../inst/include -I/home/mkln/R/x86_64-pc-linux-gnu-library/3.6/RcppArmadillo/include  `

which makes the RcppArmadillo headers visible. This seems to have no problems importing both. 
The reason I need both is that I have a lot of code written in RcppArmadillo that I don't want to port completely to AF, especially considering that I'm only just now starting to look at AF so I'm not even sure I can move my omp loops to gfor.

Thanks!

Edit: on second thought, Rcpp seems to throw issues with this approach when exporting RcppArmadillo functions, I'm guessing because it's not automatically including the headers as it would if RcppArmadillo was in LinkingTo. Any idea how to work around this? 
I would assume creating a package that only links to both arma and af would make this work? I'll try.

Edit2: ok I cant seem to be able to make a package that enables exporting functions of both types. I  guess there may be a way to mainly use RcppArmadillo and load arrayfire.h without being able to directly export its functions to R (or viceversa) but that would be a nightmare for debugging -- at least for me. any workaround is highly appreciated.

**Comment by rstub** [comment]
I had tried my approach with `Rcpp::sourceCpp()` where it worked directly, but building a package adds the additional complexity that all the headers from `LinkingTo` are added to `src/RcppExports.cpp`. The proper solution would be to make two packages. This will work as long as you don't have any functions that use both packages.

If you *must* have one package for some reason, I can offer the following approach:

1. Create a new package with `RcppArrayFire::RcppArraFire.package.skeleton()`. I use the version from `RcppArrayFire` since the skeleton is more complicated due to the configure script.
2. Manually add `RcppArmadillo` to `LinkingTo` in `DESCRIPTION`.
3. Add the `RcppArrmadillo` specific bits to  `src/Makevars.in` to read

```
AF_CXXFLAGS = @AF_CXXFLAGS@
AF_LIBS   = @AF_LIBS@

# combine with standard arguments for R
CXX_STD = CXX11
PKG_LIBS = $(AF_LIBS) $(SHLIB_OPENMP_CXXFLAGS)
PKG_CPPFLAGS = $(AF_CXXFLAGS) -I../inst/include $(SHLIB_OPENMP_CXXFLAGS) $(LAPACK_LIBS) $(BLAS_LIBS) $(FLIBS)
```

4. Add a header file with the above content and name `<pkg_name>_types.h` to `src` or `inst/include`. In the latter location you could also use `<pkg_name>.h`. See section 2.5 in the "Rcpp attributes" vignette.

5. Inhibit loading of `RcppArmadillo.h` and `RcppArrayfire.h` by adding to your header file:

```
#define RcppArmadillo__RcppArmadillo__h
#define RcppArrayFire__RcppArrayFire__h
```

This works for me using the hello world examples from the skeleton packages. Using explicit header guard names is rather brittle, though.

**Comment by mkln** [comment]
sorry for the late reply. this seems to work. thanks!
