### ISSUE TITLE
How can I solve 'R_Realloc' issue? 

### ISSUE THREAD

**Issue by YEEUM** [RInstitute/rcpparrayfire#21]
Hi, I've been trying to do stm, with codes like, 

```
kresult <- searchK(myout$documents, myout$vocab, 
                   K=20:25, 
                   prevalence = ~ created_at,
                   data=myout$meta,
)
```

then I face to the error. 

```
Beginning Spectral Initialization 
	 Calculating the gram matrix...
	 Finding anchor words...
 	......................
	 Recovering initialization...
 	........................................
Initialization complete.
....................................................................................................
Completed E-Step (15 seconds). 
Error in .sortCsparse(.Call(dtCMatrix_sparse_solve, a, b)) : 
  'R_Realloc' could not re-allocate memory (2632458240 bytes)
```

Please tell me how can I fix this problem... 
Thanks.

**Comment by rstub** [comment]
How does this problem relate to the RcppArrayFire package? Can you provide a minimal but complete example that reproduces the problem?

**Comment by YEEUM** [comment]
I'm sorry but I didn't know that this problem is related to the RcppArrayFire package untill you say it.... This ploblem occurs when I do codes below, too.

```
korstm <- stm(myout$documents, myout$vocab, K=22, 
              prevalence =~ created_at,
              data=myout$meta,
              seed=20221207,init.type="Spectral")
```

**Comment by rstub** [comment]
I am not saying that this is related to RcppArrayFire. I am actually doubting that, since there is no mention of that package in the code snippets you have posted so far. I was asking about the relationship with RcppArrayFire because you have posted it in the repository for that package. More general R questions are simply off-topic here.

More generally: If you are trying to get help with respect to programming in any kind of online forum, it is always good to provide  an example that others can follow. This example must produce the error and it should be minimal. See https://www.tidyverse.org/help/#reprex for more info on that.
