### ISSUE TITLE
Can an R function be called from RcppArrayFire?

### ISSUE THREAD

**Issue by JordiMolinsCoronado** [RInstitute/rcpparrayfire#8]
R functions can be called from Rcpp. But R functions cannot be called from RcppParallel. So the question is: can an R function be called from RcppArrayFire?

**Comment by dselivanov** [comment]
> R functions can be called from Rcpp. But R functions cannot be called from RcppParallel.

You are confusing many things. R is not thread safe. So generally you can not call any R API functions from threads.

**Comment by rstub** [comment]
I have not tired it, but it should be possible to get an `af::array` from GPU memory into main memory, convert it into a data structure that R can handle, call an R function, move the result back to GPU memory to continue computations. I would be surprised if this where very efficient, though, since moving data to and from the GPU is typically one of the main limitations with GPGPU. Does that answer your question?

**Comment by JordiMolinsCoronado** [comment]
Thank you, rstub, for your answer. I understand then that RcppArrayFire calculations have to be limited to the most time-consuming parts of the code. But then, the values should be returned to R, where other necessary R calculations may be performed. It does not make sense to try to calculate "everything" at RcppArrayFire, since R functions cannot (or it does not make sense to) be called.

I have another question, and I will open a new thread for it, if you do not mind.

**Comment by rstub** [comment]
>  I understand then that RcppArrayFire calculations have to be limited to the most time-consuming parts of the code.

I would not put it that way. GPGPU is not a silver bullet, but for some tasks it is hard to beat. Remember that the many GPU cores have to work in lock-step to be efficient. This is very different from the type of parallelism one has with CPUs, where the different cores can be treated as independent.
